backend:
  name: github
  repo: Adekoreday/MyBlog-koreythoughts-

media_folder: static/assets
public_folder: assets

collections:
  - name: koreythoughts
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tags, label: Tags}
      - { name: body, label: Body, widget: markdown }
